#ifndef REPLY_CODES
# define REPLY_CODES

# define ERR_NORECIPIENT		411
# define ERR_NOTEXTTOSEND		412
# define ERR_UNKNOWNCOMMAND		421
# define ERR_NONICKNAMEGIVEN	431
# define ERR_ERRONEUSNICKNAME	432
# define ERR_NICKNAMEINUSE		433
# define ERR_NEEDMOREPARAM		461
# define ERR_ALREADYREGISTRED	462
# define ERR_PASSWDMISMATCH		464

# define RPL_WELCOME			1

#endif
